baseURL = 'https://boringutopia.com/'
languageCode = 'en-us'
title = "boring utopia"
theme = 'archie-mod'
[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
